// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class AuditLog
{
    public string TableName { get; set; }

    public DateTime LastModified { get; set; }
}