// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class CommunicationParam
{
    public int Id { get; set; }

    public int SortOrder { get; set; }

    public int CommunicationId { get; set; }

    public string ParamKey { get; set; }

    public string DataType { get; set; }

    public bool? IsRequired { get; set; }

    public string Description { get; set; }
}