// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class Communication
{
    public int Id { get; set; }

    public string CommunicationName { get; set; }

    public string Description { get; set; }
}