// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class DeviceParameterLogs
{
    public long Id { get; set; }

    public int DeviceParameterId { get; set; }

    public string LogValue { get; set; }

    public int? YearValue { get; set; }

    public int? MonthValue { get; set; }

    public int? DayValue { get; set; }

    public int? HourValue { get; set; }

    public int? MinuteValue { get; set; }

    public int? SecondValue { get; set; }
}