// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class DeviceParameterLogs
{
    public long Id { get; set; }

    public int DeviceParameterId { get; set; }

    public string LogValue { get; set; }

    public DateTime LogTime { get; set; }

    public ushort? YearValue { get; set; }

    public byte? MonthValue { get; set; }

    public byte? DayValue { get; set; }

    public byte? HourValue { get; set; }

    public byte? MinuteValue { get; set; }

    public byte? SecondValue { get; set; }
}