// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class DeviceParameters
{
    public int Id { get; set; }

    public int DeviceId { get; set; }

    public int CommunicationId { get; set; }

    public string ParamName { get; set; }

    public string Unit { get; set; }

    public int? PollingInterval { get; set; }

    public bool? IsActive { get; set; }
}