// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace R_Factory_Tools.Models;

public partial class DeviceCommunicationParamConfig
{
    public int Id { get; set; }

    public int DeviceParameterId { get; set; }

    public int CommunicationParamId { get; set; }

    public string ConfigValue { get; set; }
}